# Generated by Django 2.2.1 on 2019-05-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('peso', models.FloatField(max_length=15)),
                ('altura', models.FloatField(max_length=15)),
                ('hp', models.PositiveIntegerField(max_length=15)),
                ('ataque', models.PositiveIntegerField(max_length=15)),
                ('defesa', models.PositiveIntegerField(max_length=15)),
                ('ataque_especial', models.PositiveIntegerField(max_length=15)),
                ('defesa_especial', models.PositiveIntegerField(max_length=15)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fraqueza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('peso', models.FloatField(max_length=15)),
                ('altura', models.FloatField(max_length=15)),
                ('hp', models.PositiveIntegerField(max_length=15)),
                ('ataque', models.PositiveIntegerField(max_length=15)),
                ('defesa', models.PositiveIntegerField(max_length=15)),
                ('ataque_especial', models.PositiveIntegerField(max_length=15)),
                ('defesa_especial', models.PositiveIntegerField(max_length=15)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Categoria')),
                ('fk_evolucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Evolucao')),
                ('fk_fraqueza', models.ManyToManyField(to='pokedex.Fraqueza')),
                ('fk_habilidade', models.ManyToManyField(to='pokedex.Habilidade')),
                ('fk_tipo', models.ManyToManyField(to='pokedex.Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='fraqueza',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.Tipo'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='fk_fraqueza',
            field=models.ManyToManyField(to='pokedex.Fraqueza'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='fk_habilidade',
            field=models.ManyToManyField(to='pokedex.Habilidade'),
        ),
        migrations.AddField(
            model_name='evolucao',
            name='fk_tipo',
            field=models.ManyToManyField(to='pokedex.Tipo'),
        ),
    ]
