# Generated by Django 2.2.1 on 2019-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='imagem',
            field=models.FileField(default=1, upload_to='fotos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='imagem',
            field=models.FileField(default=1, upload_to='fotos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='ataque',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='ataque_especial',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='defesa',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='defesa_especial',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='hp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ataque',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ataque_especial',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defesa',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defesa_especial',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(),
        ),
    ]
